package prs

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"sync"
	"testing"
	"time"

	githubv39 "github.com/google/go-github/v39/github"

	"github.com/gke-labs/gemini-for-kubernetes-development/factory/pkg/commands/watch/conventions"
)

// TestEvaluate_BotReplyDoesNotSuppressFeedback covers the loop the removed
// whole-conversation watermark was added for, and who closes it now.
//
// The loop: an agent reads a comment, decides no code change is needed, and
// says so in the thread. Nothing is pushed, so the commit check cannot help,
// and without some record the same feedback is sent to an agent forever.
//
// The record used to be "the watcher has said something since this comment",
// which was true of any comment it posted for any reason, about any other
// comment. It is now the 👍 on the comment itself, which says what became of
// that comment and nothing else.
func TestEvaluate_BotReplyDoesNotSuppressFeedback(t *testing.T) {
	tests := []struct {
		name string
		// reactions are the marks on the human's comment.
		reactions  []*githubv39.Reaction
		wantQueued bool
	}{
		{
			// The reply is evidence about the thread, not about this comment.
			// Nothing marked the comment, so nothing says it was handled.
			name:       "a later bot reply does not answer an unmarked comment",
			wantQueued: true,
		},
		{
			name:       "the mark left when the reply was written does",
			reactions:  []*githubv39.Reaction{watcherReaction(conventions.ReactionResolved)},
			wantQueued: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			srv := &botReplyServer{reactions: tc.reactions}
			tempDir := t.TempDir()

			s, _ := newTestScanner(t, tempDir, testOpts{
				GitHub:         srv.start(t),
				BotUsers:       []string{"bot1"},
				GitHubLogin:    "bot1",
				TriggerLabel:   "factory",
				ReviewerLogins: []string{"reviewbot"},
			})

			s.evaluateAll(context.Background(), []*githubv39.Issue{{
				Number:    githubv39.Int(inlinePRNumber),
				Assignees: []*githubv39.User{{Login: stringPtr("bot1")}},
				Labels:    []*githubv39.Label{{Name: stringPtr("factory")}},
			}})

			if queued := taskWasQueued(t, tempDir, "task-pr-10-comments.yaml"); queued != tc.wantQueued {
				t.Errorf("address-comments task queued = %v, want %v", queued, tc.wantQueued)
			}
		})
	}
}

const feedbackCommentID = int64(444)

// botReplyServer is a GitHub stand-in for a pull request carrying one human
// comment and, after it, a reply from the watcher's own account that pushed no
// commit.
type botReplyServer struct {
	mu sync.Mutex

	reactions []*githubv39.Reaction
}

func (s *botReplyServer) start(t *testing.T) *githubv39.Client {
	t.Helper()

	base := "/repos/test-owner/test-repo"
	commitTime := time.Now().Add(-3 * time.Hour)
	commentTime := time.Now().Add(-2 * time.Hour)
	replyTime := time.Now().Add(-1 * time.Hour)
	reactionsPath := fmt.Sprintf("%s/issues/comments/%d/reactions", base, feedbackCommentID)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")

		switch {
		case r.Method == http.MethodGet && r.URL.Path == reactionsPath:
			s.mu.Lock()
			defer s.mu.Unlock()
			_ = json.NewEncoder(w).Encode(s.reactions)

		case r.URL.Path == fmt.Sprintf("%s/pulls/%d", base, inlinePRNumber):
			_ = json.NewEncoder(w).Encode(&githubv39.PullRequest{
				Number:    githubv39.Int(inlinePRNumber),
				Mergeable: githubv39.Bool(true),
				State:     stringPtr("open"),
				User:      &githubv39.User{Login: stringPtr("bot1")},
				Head:      &githubv39.PullRequestBranch{SHA: stringPtr(inlineHeadSHA)},
				CreatedAt: timePtr(time.Now().Add(-24 * time.Hour)),
			})

		case r.URL.Path == fmt.Sprintf("%s/pulls/%d/commits", base, inlinePRNumber):
			_ = json.NewEncoder(w).Encode([]*githubv39.RepositoryCommit{{
				SHA:    stringPtr(inlineHeadSHA),
				Commit: &githubv39.Commit{Committer: &githubv39.CommitAuthor{Date: timePtr(commitTime)}},
			}})

		case r.URL.Path == fmt.Sprintf("%s/issues/%d/comments", base, inlinePRNumber):
			_ = json.NewEncoder(w).Encode([]*githubv39.IssueComment{
				{
					ID:        githubv39.Int64(feedbackCommentID),
					User:      &githubv39.User{Login: stringPtr("reviewer-human")},
					Body:      stringPtr("why is this not a constant?"),
					CreatedAt: timePtr(commentTime),
				},
				{
					ID:        githubv39.Int64(feedbackCommentID + 1),
					User:      &githubv39.User{Login: stringPtr("bot1")},
					Body:      stringPtr("It is deliberate: the value differs per deployment.\n\n*(This comment was generated by factory)*"),
					CreatedAt: timePtr(replyTime),
				},
			})

		case r.URL.Path == fmt.Sprintf("%s/pulls/%d/reviews", base, inlinePRNumber):
			_ = json.NewEncoder(w).Encode([]*githubv39.PullRequestReview{})

		default:
			// Reaction writes, check runs, statuses, labels and anything else
			// the evaluation touches on its way past.
			_ = json.NewEncoder(w).Encode([]any{})
		}
	}))
	t.Cleanup(server.Close)

	gh := githubv39.NewClient(nil)
	gh.BaseURL, _ = url.Parse(server.URL + "/")
	return gh
}
