apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overseer-sandbox
rules:
- apiGroups:
  - "agents.x-k8s.io"
  resources:
  - sandboxes
  verbs:
  - get
  - update
  - patch
  - list
  - watch
  - create
  - delete
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]