package tasks

import (
	"bytes"
	"fmt"
)

type Repo struct {
	CloneURL string
}

type Issue struct {
	Number  int
	HTMLURL string
	Title   string
	Body    string
}

type IssueComment struct {
	UserLogin string
	Body      string
}

type FixIssueParams struct {
	Repo          Repo
	Issue         Issue
	IssueComments []IssueComment
	Instruction   string
	Branch        string
	Models        []string
	DraftPR       bool
	// PRLabel is the comma-separated label set the PR must carry.
	PRLabel string
	NoPR    bool
	// TriggerLabel names the agent in the "generated by" line. It is kept
	// apart from PRLabel, which also carries the parent issue's labels and
	// so reads as e.g. "overseer,priority/medium,area/release".
	TriggerLabel string
	// Disclose asks for the "generated by" line in the PR description.
	Disclose bool
}

func GetFixIssueScript() ([]byte, error) {
	return getScriptWithDefaults("fix_issue.sh")
}

func RenderFixIssuePrompt(params FixIssueParams) ([]byte, error) {
	if len(params.Models) == 0 {
		params.Models = DefaultModels
	}

	promptTmpl, err := getPromptTemplate("fix_issue.txt")
	if err != nil {
		return nil, fmt.Errorf("getting prompt template: %w", err)
	}
	var pBuf bytes.Buffer
	if err := promptTmpl.Execute(&pBuf, params); err != nil {
		return nil, fmt.Errorf("executing prompt template: %w", err)
	}

	return pBuf.Bytes(), nil
}

type FailedRun struct {
	ID   int64
	Name string
	URL  string
}

type PRComment struct {
	ID        int64
	UserLogin string
	CreatedAt string
	Body      string
}

type PullRequest struct {
	Number int
	URL    string
	Title  string
	Body   string
}

type InvestigateParams struct {
	PullRequest   PullRequest
	FailedRuns    []FailedRun
	IssueComments []PRComment
	// Instruction is the caller's request (the --prompt flag), rendered
	// ahead of the standard investigation instructions.
	Instruction  string
	Models       []string
	TriggerLabel string
	// Disclose asks for the "generated by" footer on the posted report.
	Disclose bool
}

func GetInvestigateScript() ([]byte, error) {
	return getScriptWithDefaults("investigate_failures.sh")
}

func RenderInvestigatePrompt(params InvestigateParams) ([]byte, error) {
	if len(params.Models) == 0 {
		params.Models = DefaultModels
	}

	promptTmpl, err := getPromptTemplate("investigate_failures.txt")
	if err != nil {
		return nil, fmt.Errorf("getting prompt template: %w", err)
	}
	var pBuf bytes.Buffer
	if err := promptTmpl.Execute(&pBuf, params); err != nil {
		return nil, fmt.Errorf("executing prompt template: %w", err)
	}

	return pBuf.Bytes(), nil
}

type RepositoryCommit struct {
	SHA     string
	Message string
}

type PullRequestComment struct {
	Path     string
	DiffHunk string
	Body     string
}

type PRReview struct {
	ID                  int64
	UserLogin           string
	Body                string
	PullRequestComments []PullRequestComment
}

type AddressFeedbackParams struct {
	PullRequest           PullRequest
	RepositoryCommits     []RepositoryCommit
	OldIssueComments      []PRComment
	IssueComments         []PRComment
	OldPullRequestReviews []PRReview
	PullRequestReviews    []PRReview
	Models                []string
	TriggerLabel          string
	// Disclose asks for the "generated by" footer on the posted replies.
	Disclose bool
}

func GetAddressFeedbackScript() ([]byte, error) {
	return getScriptWithDefaults("address_feedback.sh")
}

func RenderAddressFeedbackPrompt(params AddressFeedbackParams) ([]byte, error) {
	if len(params.Models) == 0 {
		params.Models = DefaultModels
	}

	promptTmpl, err := getPromptTemplate("address_feedback.txt")
	if err != nil {
		return nil, fmt.Errorf("getting prompt template: %w", err)
	}
	var pBuf bytes.Buffer
	if err := promptTmpl.Execute(&pBuf, params); err != nil {
		return nil, fmt.Errorf("executing prompt template: %w", err)
	}

	return pBuf.Bytes(), nil
}
